"$schema" = 'https://starship.rs/config-schema.json'
format = "$custom"
add_newline = false

[custom.prefix_active]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" = "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "bg:#8bd5ca fg:#181926 bold"

[custom.session_normal]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" != "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "fg:#6e738d"
