name = "Tokyo Night"
description = "A clean, dark Neovim-inspired theme that celebrates the lights of Downtown Tokyo"
author = "Tokyo Night"
variant = "dark"
window_separator = " • "

[[swatches]]
name = "Blue"
hex = "#7aa2f7"

[[swatches]]
name = "Cyan"
hex = "#7dcfff"

[[swatches]]
name = "Green"
hex = "#73daca"

[[swatches]]
name = "Magenta"
hex = "#bb9af7"

[[swatches]]
name = "Yellow"
hex = "#e0af68"

