name = "Catppuccin Mocha"
description = "Soothing pastel dark theme with deep contrast and rich vibrant accents"
author = "Catppuccin Org"
variant = "dark"
window_separator = " • "

[[swatches]]
name = "Teal"
hex = "#94e2d5"

[[swatches]]
name = "Blue"
hex = "#89b4fa"

[[swatches]]
name = "Green"
hex = "#a6e3a1"

[[swatches]]
name = "Yellow"
hex = "#f9e2af"

[[swatches]]
name = "Mauve"
hex = "#cba6f7"

[[swatches]]
name = "Surface"
hex = "#313244"

