"$schema" = 'https://starship.rs/config-schema.json'
format = "$custom$time"
add_newline = false

[custom.prefix_active]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" = "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "bg:#b4637a fg:#faf4ed bold"

[custom.session_normal]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" != "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "fg:#797593"

[time]
disabled = false
format = "[$time]($style) "
style = "fg:#56949f"
time_format = "%H:%M:%S"
