name = "Catppuccin Latte"
description = "Crisp, bright light theme with cheerful and soft contrast"
author = "Catppuccin Org"
variant = "light"
window_separator = " • "

[[swatches]]
name = "Teal"
hex = "#179299"

[[swatches]]
name = "Blue"
hex = "#1e66f5"

[[swatches]]
name = "Green"
hex = "#40a02b"

[[swatches]]
name = "Peach"
hex = "#fe640b"

[[swatches]]
name = "Mauve"
hex = "#8839ef"

