name = "Kanagawa"
description = "Elegant dark theme inspired by the colors of Katsushika Hokusai's woodblock print"
author = "rebelot"
variant = "dark"
window_separator = " • "

[[swatches]]
name = "Wave Blue"
hex = "#7e9cd8"

[[swatches]]
name = "Spring Green"
hex = "#98bb6c"

[[swatches]]
name = "Surimi Orange"
hex = "#ffa066"

[[swatches]]
name = "Sakura Pink"
hex = "#d27e99"

[[swatches]]
name = "Oni Violet"
hex = "#957fb8"

