name = "Dracula"
description = "Famous dark theme for hackers with iconic purple, cyan and neon accents"
author = "Zeno Rocha"
variant = "dark"
window_separator = " • "

[[swatches]]
name = "Purple"
hex = "#bd93f9"

[[swatches]]
name = "Cyan"
hex = "#8be9fd"

[[swatches]]
name = "Green"
hex = "#50fa7b"

[[swatches]]
name = "Pink"
hex = "#ff79c6"

[[swatches]]
name = "Yellow"
hex = "#f1fa8c"

