"$schema" = 'https://starship.rs/config-schema.json'
format = "$custom$time"
add_newline = false

[custom.prefix_active]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" = "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "bg:#88c0d0 fg:#2e3440 bold"

[custom.session_normal]
when = 'test "${TMUX_CLIENT_PREFIX:-0}" != "1"'
command = 'printf "󰇄 %s" "${TMUX_SESSION_NAME:-tmux}"'
format = "[$output]($style) "
style = "fg:#4c566a"

[time]
disabled = false
format = "[$time]($style) "
style = "fg:#81a1c1"
time_format = "%H:%M:%S"
